# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RolloutCli < Formula
  desc "Publish your articles everywhere"
  homepage ""
  version "0.0.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/pjeziorowski/rollout/releases/download/v0.0.4/rollout_0.0.4_darwin_amd64.tar.gz"
    sha256 "941b06bf4990bdd4d46b1c2ca9c50c7fc20f832751b8b69a32267c57a81f2229"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/pjeziorowski/rollout/releases/download/v0.0.4/rollout_0.0.4_darwin_arm64.tar.gz"
    sha256 "ce9114b72abff0f15477e91dbff3b49cfe0595ccfd83976b4d43d89e1b1689ec"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pjeziorowski/rollout/releases/download/v0.0.4/rollout_0.0.4_linux_amd64.tar.gz"
    sha256 "42548eb3f0a9f2d5ed59da9f208dc7cf05241d2b6d65157683db0ac27fa987a3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/pjeziorowski/rollout/releases/download/v0.0.4/rollout_0.0.4_linux_arm64.tar.gz"
    sha256 "184a3b7b4abe347af21d0f85f4386fac24e870b168080df2d9e08c95c8cde7e1"
  end

  def install
    bin.install "rollout"
  end
end
