# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RolloutCli < Formula
  desc "Publish your articles everywhere"
  homepage ""
  version "0.0.6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/pjeziorowski/rollout/releases/download/v0.0.6/rollout_0.0.6_darwin_amd64.tar.gz"
    sha256 "5a92a016399fc8dbffccb8a18819f83253da73d443c66c8af98f294426ab7376"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/pjeziorowski/rollout/releases/download/v0.0.6/rollout_0.0.6_darwin_arm64.tar.gz"
    sha256 "932b7629383a1d959bd2eb0775eefa107b2552d86c50bdcdfa3d9c910d2ddb19"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pjeziorowski/rollout/releases/download/v0.0.6/rollout_0.0.6_linux_amd64.tar.gz"
    sha256 "c0c1edf5c206fe14c63f4ddb1f7c1546c0df4abc32b968d220db0678f3b78779"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/pjeziorowski/rollout/releases/download/v0.0.6/rollout_0.0.6_linux_arm64.tar.gz"
    sha256 "5a07399229d1361784062bd7776fb7def9895465aa9f0dd6c06797215a26da8d"
  end

  def install
    bin.install "rollout"
  end
end
